-- Table: market_lexicons (Dynamic Domain Vocabulary & Vernacular)
CREATE TABLE IF NOT EXISTS market_lexicons (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    domain VARCHAR(64) NOT NULL,
    term VARCHAR(128) NOT NULL,
    category VARCHAR(64) DEFAULT 'vernacular',
    created_by VARCHAR(64) DEFAULT 'system',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT uq_domain_term UNIQUE (domain, term)
);

CREATE INDEX IF NOT EXISTS idx_market_lexicons_domain ON market_lexicons(domain);
CREATE INDEX IF NOT EXISTS idx_market_lexicons_term ON market_lexicons(term);

-- Table: industry_taxonomies (Dynamic Category Mappings)
CREATE TABLE IF NOT EXISTS industry_taxonomies (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    industry_code VARCHAR(64) NOT NULL UNIQUE,
    industry_name VARCHAR(128) NOT NULL,
    keywords TEXT[] DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed Initial Core Lexicons
INSERT INTO market_lexicons (domain, term, category, created_by) VALUES
('common_vi', 'hướng dẫn', 'intent', 'system'),
('common_vi', 'cách làm', 'intent', 'system'),
('common_vi', 'kinh nghiệm', 'intent', 'system'),
('common_vi', 'đánh giá', 'intent', 'system'),
('common_vi', 'review', 'intent', 'system'),
('common_vi', 'chi phí', 'commercial', 'system'),
('common_vi', 'giá bao nhiêu', 'commercial', 'system'),
('common_vi', 'xin giá', 'commercial', 'system'),
('common_vi', 'mua ở đâu', 'commercial', 'system'),
-- Tech, SaaS & Automation Vertical
('tech', 'ai agent', 'topic', 'system'),
('tech', 'chatbot', 'topic', 'system'),
('tech', 'ai agent CSKH', 'topic', 'system'),
('tech', 'chatbot chốt đơn', 'topic', 'system'),
('tech', 'zalo', 'platform', 'system'),
('tech', 'token', 'technical', 'system'),
('tech', 'n8n', 'tool', 'system'),
('tech', 'dify', 'tool', 'system'),
('tech', 'make', 'tool', 'system'),
('tech', 'make.com', 'tool', 'system'),
('tech', 'zapier', 'tool', 'system'),
('tech', 'flowise', 'tool', 'system'),
('tech', 'langchain', 'tool', 'system'),
('tech', 'rpa', 'tool', 'system'),
('tech', 'tự động hóa', 'technical', 'system'),
('tech', 'webhook', 'technical', 'system'),
('tech', 'crm automation', 'technical', 'system'),
('tech', 'quét lead', 'intent', 'system'),
('tech', 'auto inbox', 'intent', 'system'),
('tech', 'auto comment', 'intent', 'system'),
('tech', 'bot bán hàng', 'intent', 'system'),
('tech', 'bán hàng tự động', 'intent', 'system'),
('tech', 'cskh', 'domain', 'system'),
('tech', 'phần mềm', 'domain', 'system'),
-- E-Commerce & TikTok Shop Vertical
('ecommerce', 'tiktok shop', 'platform', 'system'),
('ecommerce', 'shopee', 'platform', 'system'),
('ecommerce', 'lazada', 'platform', 'system'),
('ecommerce', 'chốt đơn', 'vernacular', 'system'),
('ecommerce', 'kho hàng', 'vernacular', 'system'),
('ecommerce', 'vận đơn', 'vernacular', 'system'),
('ecommerce', 'livestream', 'vernacular', 'system'),
('ecommerce', 'affiliate', 'vernacular', 'system'),
('ecommerce', 'giỏ hàng', 'vernacular', 'system'),
('ecommerce', 'gắn giỏ hàng', 'vernacular', 'system'),
('ecommerce', 'seeding', 'vernacular', 'system'),
('ecommerce', 'nguồn sỉ', 'vernacular', 'system'),
('ecommerce', 'kho sỉ', 'vernacular', 'system'),
('ecommerce', 'dropshipping', 'vernacular', 'system'),
('ecommerce', 'flash sale', 'vernacular', 'system'),
('ecommerce', 'voucher', 'vernacular', 'system'),
('ecommerce', 'ads tiktok', 'vernacular', 'system'),
('ecommerce', 'kéo tương tác', 'vernacular', 'system'),
('ecommerce', 'hỏa tốc', 'vernacular', 'system'),
('ecommerce', 'hoàn đơn', 'vernacular', 'system'),
('ecommerce', 'bom hàng', 'vernacular', 'system'),
-- Fashion & Apparel Vertical
('fashion', 'local brand', 'vernacular', 'system'),
('fashion', 'linen', 'material', 'system'),
('fashion', 'áo linen', 'product', 'system'),
('fashion', 'đầm thiết kế', 'product', 'system'),
('fashion', 'thời trang công sở', 'product', 'system'),
('fashion', 'xưởng may', 'supply_chain', 'system'),
('fashion', 'order taobao', 'supply_chain', 'system'),
('fashion', 'sỉ quần áo', 'supply_chain', 'system'),
('fashion', 'set đồ', 'style', 'system'),
('fashion', 'vải linen', 'material', 'system'),
('fashion', 'phong cách tối giản', 'style', 'system'),
('fashion', 'oversize', 'style', 'system'),
('fashion', 'outfit', 'style', 'system'),
('fashion', 'chân váy', 'product', 'system'),
('fashion', 'blazer', 'product', 'system'),

-- Foreign Stopwords (Dynamic Language Filter Seeds)
('foreign_stopwords', 'como', 'stopwords_pt', 'system'),
('foreign_stopwords', 'funcionam', 'stopwords_pt', 'system'),
('foreign_stopwords', 'chegou', 'stopwords_pt', 'system'),
('foreign_stopwords', 'novos', 'stopwords_pt', 'system'),
('foreign_stopwords', 'veja', 'stopwords_pt', 'system'),
('foreign_stopwords', 'agentes', 'stopwords_pt', 'system'),
('foreign_stopwords', 'autonomos', 'stopwords_pt', 'system'),
('foreign_stopwords', 'autônomos', 'stopwords_pt', 'system'),
('foreign_stopwords', 'você', 'stopwords_pt', 'system'),
('foreign_stopwords', 'voce', 'stopwords_pt', 'system'),
('foreign_stopwords', 'fazer', 'stopwords_pt', 'system'),
('foreign_stopwords', 'curso', 'stopwords_pt', 'system'),
('foreign_stopwords', 'formation', 'stopwords_fr', 'system'),
('foreign_stopwords', 'complète', 'stopwords_fr', 'system'),
('foreign_stopwords', 'debutant', 'stopwords_fr', 'system'),
('foreign_stopwords', 'débutant', 'stopwords_fr', 'system'),
('foreign_stopwords', 'cara', 'stopwords_id', 'system'),
('foreign_stopwords', 'yang', 'stopwords_id', 'system'),
('foreign_stopwords', 'untuk', 'stopwords_id', 'system')
ON CONFLICT (domain, term) DO NOTHING;

INSERT INTO industry_taxonomies (industry_code, industry_name, keywords) VALUES
('tech', 'Tech & Electronics', ARRAY['ai', 'software', 'agent', 'bot', 'app', 'tool', 'hardware', 'laptop', 'chatgpt', 'gpt', 'claude', 'gemini', 'automation', 'blender', 'figma', 'notion', 'saas', 'api', 'cloud', 'chatbot', 'prompt', 'no code', 'tự động hóa', 'công nghệ', 'máy tính', 'điện thoại', 'phần mềm', 'lập trình']),
('ecommerce', 'E-Commerce & Retail', ARRAY['shop', 'shopee', 'lazada', 'order', 'shipping', 'tiki', 'sendo', 'affiliate', 'freeship', 'tiktok shop', 'đơn hàng', 'chốt đơn', 'bán hàng', 'gian hàng', 'tồn kho', 'giá sỉ', 'nhập hàng', 'mã giảm giá', 'khách hàng', 'doanh thu', 'tỷ lệ chuyển đổi']),
('fashion', 'Apparel & Accessories', ARRAY['fashion', 'clothing', 'linen', 'dress', 'shirt', 'outfit', 'style', 'cotton', 'jeans', 'streetwear', 'local brand', 'quần áo', 'thời trang', 'phối đồ', 'phụ kiện', 'chất liệu', 'mix đồ', 'sơ mi', 'đồ nỉ']),
('education', 'Education & Training', ARRAY['course', 'tutorial', 'ielts', 'toeic', 'khóa học', 'đào tạo', 'hướng dẫn', 'tiếng anh', 'phát âm', 'ngữ pháp', 'từ vựng', 'luyện thi', 'giáo viên', 'học sinh', 'sinh viên', 'bài giảng', 'kỹ năng', 'chứng chỉ', 'lớp học', 'tự học', 'giáo trình', 'đại học']),
('beauty', 'Beauty & Personal Care', ARRAY['skincare', 'makeup', 'serum', 'toner', 'salon', 'spa', 'mỹ phẩm', 'dưỡng da', 'sữa rửa mặt', 'kem chống nắng', 'trị mụn', 'trang điểm', 'nước hoa', 'nhuộm tóc', 'tẩy tóc', 'làm đẹp', 'dưỡng ẩm', 'tẩy trang', 'mặt nạ', 'chăm sóc da']),
('finance', 'Financial Services', ARRAY['finance', 'bank', 'crypto', 'tài chính', 'đầu tư', 'ngân hàng', 'chứng khoán', 'giá vàng', 'lãi suất', 'tín dụng', 'thẻ tín dụng', 'tiết kiệm', 'bảo hiểm', 'cổ phiếu', 'tỷ giá', 'quỹ đầu tư', 'trái phiếu', 'ví điện tử']),
('news', 'News & Current Affairs', ARRAY['thời sự', 'tin nóng', 'tin tức', 'bản tin', 'chính trị', 'pháp luật', 'tòa án', 'công an', 'quốc hội', 'chính phủ', 'thiên tai', 'bão lụt', 'giao thông', 'tai nạn']),
('sports', 'Sports', ARRAY['esports', 'marathon', 'pickleball', 'champions league', 'world cup', 'sea games', 'bóng đá', 'thể thao', 'thi đấu', 'giải đấu', 'tuyển việt nam', 'ngoại hạng anh', 'cầu thủ', 'huấn luyện viên', 'tỷ số', 'vòng bảng', 'bàn thắng', 'chạy bộ']),
('entertainment', 'Entertainment & Media', ARRAY['showbiz', 'netflix', 'kpop', 'idol', 'anime', 'concert', 'gameshow', 'liên quân mobile', 'phim mới', 'diễn viên', 'ca sĩ', 'âm nhạc', 'nghệ sĩ', 'rap việt', 'truyện tranh', 'game mobile', 'phòng vé']),
('health', 'Health & Wellness', ARRAY['wellness', 'yoga', 'vaccine', 'sức khỏe', 'bệnh viện', 'bác sĩ', 'dinh dưỡng', 'tập gym', 'giấc ngủ', 'tâm lý', 'thực phẩm chức năng', 'dịch bệnh', 'giảm cân', 'thiền định', 'khám bệnh']),
('food', 'Food & Beverage', ARRAY['đồ ăn', 'quán ăn', 'nhà hàng', 'ẩm thực', 'công thức nấu', 'nấu ăn', 'cà phê', 'trà sữa', 'ăn uống', 'món ngon', 'đặt món', 'review quán', 'nguyên liệu', 'đồ uống']),
('travel', 'Travel & Hospitality', ARRAY['tour', 'homestay', 'resort', 'visa', 'checkin', 'du lịch', 'khách sạn', 'vé máy bay', 'điểm đến', 'lịch trình', 'hộ chiếu', 'nghỉ dưỡng', 'vé tàu']),
('realestate', 'Real Estate & Construction', ARRAY['bất động sản', 'căn hộ', 'chung cư', 'nhà phố', 'đất nền', 'sổ hồng', 'thuê nhà', 'môi giới', 'xây dựng', 'nội thất', 'quy hoạch', 'giá nhà']),
('auto', 'Automotive & Mobility', ARRAY['vinfast', 'test drive', 'xe máy', 'ô tô', 'xe điện', 'xe hơi', 'lái xe', 'bảng giá xe', 'đăng kiểm', 'phụ tùng', 'xe tải', 'bảo dưỡng xe', 'xe ga'])
ON CONFLICT (industry_code) DO NOTHING;
